networks:
  spark-network:
    driver: bridge

volumes:
  spark-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/spark-data

  spark-events:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/spark-events

  spark-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/spark-conf

services:
  spark-master:
    image: crpi-cvpgqjd9gzkmtsyd.cn-beijing.personal.cr.aliyuncs.com/data_dev/spark:3.5.1
    platform: linux/amd64
    container_name: spark-master
    hostname: spark-master
    working_dir: /opt/spark/work-dir
    user: root
    environment:
      - HOME=/home/spark
    networks:
      - spark-network
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - spark-data:/opt/spark/work-dir
      - spark-events:/tmp/spark-events
      - spark-conf:/opt/spark/conf
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    restart: unless-stopped

  spark-worker-1:
    image: crpi-cvpgqjd9gzkmtsyd.cn-beijing.personal.cr.aliyuncs.com/data_dev/spark:3.5.1
    platform: linux/amd64
    container_name: spark-worker-1
    hostname: spark-worker-1
    networks:
      - spark-network
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - spark-data:/opt/spark/work-dir
      - spark-events:/tmp/spark-events
      - spark-conf:/opt/spark/conf
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    restart: unless-stopped

  spark-worker-2:
    image: crpi-cvpgqjd9gzkmtsyd.cn-beijing.personal.cr.aliyuncs.com/data_dev/spark:3.5.1
    platform: linux/amd64
    container_name: spark-worker-2
    hostname: spark-worker-2
    networks:
      - spark-network
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - spark-data:/opt/spark/work-dir
      - spark-events:/tmp/spark-events
      - spark-conf:/opt/spark/conf
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    restart: unless-stopped

  spark-history:
    image: crpi-cvpgqjd9gzkmtsyd.cn-beijing.personal.cr.aliyuncs.com/data_dev/spark:3.5.1
    platform: linux/amd64
    container_name: spark-history
    hostname: spark-history
    networks:
      - spark-network
    depends_on:
      - spark-master
    ports:
      - "18080:18080"
    volumes:
      - spark-events:/tmp/spark-events
      - spark-conf:/opt/spark/conf
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.history.HistoryServer
    restart: unless-stopped

